image: gradle:4.10-jdk8-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - echo "Starting.."
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  # Remove caches
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - gradle build

checkstyle:
  stage: test
  script: gradle checkstyleMain checkstyleTest
  allow_failure: true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "ri-bot/"'

test:
  stage: test
  script:
    - gradle check
    - gradle jacocoTestReport
    - cat build/jacocoHtml/index.html

  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "ri-bot/"'

Deployment:
  image: ruby:2.4
  stage: deploy
  only:
    - master
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
    - heroku run --app $HEROKU_APPNAME migrate
  environment:
    name: production
    url: $HEROKU_APP_HOST